from __future__ import annotations

import json
import re
import unicodedata
from copy import deepcopy
from typing import Any

HALLOWEEN_TIERS: list[dict[str, Any]] = [{'id': 'S', 'label': 'S', 'decks': ['Mitsurugi', 'Memento', 'Darklord', 'Invoked']},
 {'id': 'A',
  'label': 'A',
  'decks': ['D/D/D', 'Archfiend', 'Fiendsmith', 'Unchained', 'Apophis', 'Yubel', 'Hecahands', 'Azamina', 'Ashtra']},
 {'id': 'B',
  'label': 'B',
  'decks': ['K9',
            'Snake-Eye',
            'Phantom Knights',
            'Mimighoul',
            'Clown Crew',
            'Thunder Dragon',
            'Goblin Biker',
            'Eldlich',
            'Zombie',
            'Wight']},
 {'id': 'B-', 'label': 'B-', 'decks': ['Gimmick Puppet', 'Shaddoll', 'Ogdoadic', 'Nemleria', 'Regenesis', 'Fabled', 'Umbral Horror']},
 {'id': 'C+',
  'label': 'C+',
  'decks': ['Generaider', 'Dark World', 'Mayakashi', 'Shiranui', 'Call of the Haunted / Pumpking', 'Magical Musket']},
 {'id': 'C',
  'label': 'C',
  'decks': ['Altergeist',
            'Evil Eye',
            'Blackwing',
            'Eyes Restrict / Relinquished',
            'Evil HERO',
            'Vampire',
            'Scareclaw',
            'Myutant',
            'Fluffal / Frightfur']},
 {'id': 'D', 'label': 'D', 'decks': ['Arcana Force', 'Spirit Message', 'Ghostrick']}]
HALLOWEEN_STAPLES: list[str] = ['Yo-kai Girl',
 'Knightmare',
 'Danger!',
 'Paleozoic',
 'Predaplant',
 'Entity',
 'Evilswarm',
 'True King',
 'Halloween Staples',
 'Zombie Staples']
HALLOWEEN_BANLIST_OVERRIDES: dict[str, list[dict[str, Any]]] = {'Darklord': [{'card': 'Forbidden Crown', 'limit': 3}],
 'Archfiend': [{'card': 'Hot Red Dragon Archfiend King Calamity', 'limit': 1}],
 'Yubel': [{'card': 'Phantom of Yubel', 'limit': 2}],
 'K9': [{'card': 'K9-04 Noroi', 'limit': 1},
        {'card': 'K9-66a Jokul', 'limit': 2},
        {'card': 'A Case for K9', 'limit': 1}],
 'Snake-Eye': [{'card': 'Original Sinful Spoils - Snake-Eye', 'limit': 1}, {'card': 'Bonfire', 'limit': 2}],
 'Thunder Dragon': [{'card': 'Gold Sarcophagus', 'limit': 2}, {'card': 'Chaos Space', 'limit': 2}],
 'Eldlich': [{'card': 'Skill Drain', 'limit': 2},
             {'card': 'Rivalry of Warlords', 'limit': 2},
             {'card': 'Gozen Match', 'limit': 2},
             {'card': 'There Can Be Only One', 'limit': 1}],
 'Zombie': [{'card': 'Chaos Ruler, the Chaotic Magical Dragon', 'limit': 1},
            {'card': 'That Grass Looks Greener', 'limit': 2}],
 'Wight': [{'card': 'One for One', 'limit': 2}, {'card': 'That Grass Looks Greener', 'limit': 2}],
 'Gimmick Puppet': [{'card': 'CXyz Gimmick Puppet Fanatix Machinix', 'limit': 1},
                    {'card': 'Gimmick Puppet Nightmare', 'limit': 1},
                    {'card': 'Number 40: Gimmick Puppet of Strings', 'limit': 2},
                    {'card': 'Number C40: Gimmick Puppet of Dark Strings', 'limit': 2}],
 'Shaddoll': [{'card': 'Instant Fusion', 'limit': 2}, {'card': 'That Grass Looks Greener', 'limit': 2}],
 'Ogdoadic': [{'card': 'King of the Feral Imps', 'limit': 1}, {'card': 'Foolish Burial', 'limit': 2}],
 'Fabled': [{'card': 'Card Destruction', 'limit': 2},
            {'card': 'T.G. Hyper Librarian', 'limit': 2},
            {'card': 'Borreload Savage Dragon', 'limit': 1}],
 'Dark World': [{'card': 'Card Destruction', 'limit': 2}],
 'Altergeist': [{'card': "Vanity's Emptiness", 'limit': 1},
                {'card': 'Imperial Order', 'limit': 1},
                {'card': 'Summon Limit', 'limit': 1}],
 'Evil Eye': [{'card': 'Kaiser Colosseum', 'limit': 1}],
 'Blackwing': [{'card': 'Blackwing - Gofu the Vague Shadow', 'limit': 1}],
 'Evil HERO': [],
 'Vampire': [{'card': 'Card of Safe Return', 'limit': 1}],
 'Scareclaw': [{'card': 'Knightmare Gryphon', 'limit': 1}],
 'Myutant': [{'card': 'Dimension Shifter', 'limit': 2}, {'card': 'Return from the Different Dimension', 'limit': 1}],
 'Fluffal / Frightfur': [],
 'Arcana Force': [{'card': 'Sixth Sense', 'limit': 1}],
 'Spirit Message': [{'card': 'Mystic Mine', 'limit': 1},
                    {'card': 'One Day of Peace', 'limit': 2},
                    {'card': 'Card of Demise', 'limit': 2}],
 'Ghostrick': [{'card': 'Royal Oppression', 'limit': 1},
               {'card': 'One Day of Peace', 'limit': 2},
               {'card': 'Card of Demise', 'limit': 2}],
 'Call of the Haunted / Pumpking': [{'card': 'Card of Safe Return', 'limit': 1}],
 'True King': [{'card': 'True King of All Calamities', 'limit': 1}]}
HALLOWEEN_GLOBAL_BANS: list[str] = ['Predaplant Verte Anaconda']
GENERIC_HALLOWEEN_STAPLES: list[str] = ['Forbidden Crown',
 'Bonfire',
 'Gold Sarcophagus',
 'Chaos Space',
 'Skill Drain',
 'Rivalry of Warlords',
 'Gozen Match',
 'There Can Be Only One',
 'Chaos Ruler, the Chaotic Magical Dragon',
 'That Grass Looks Greener',
 'One for One',
 'Instant Fusion',
 'Foolish Burial',
 'King of the Feral Imps',
 'Card Destruction',
 'T.G. Hyper Librarian',
 'Borreload Savage Dragon',
 "Vanity's Emptiness",
 'Imperial Order',
 'Summon Limit',
 'Kaiser Colosseum',
 'Card of Safe Return',
 'Knightmare Gryphon',
 'Dimension Shifter',
 'Return from the Different Dimension',
 'Sixth Sense',
 'Mystic Mine',
 'One Day of Peace',
 'Card of Demise',
 'Royal Oppression']
ZOMBIE_STAPLES: list[str] = ['Doomking Balerdroch',
 'Uni-Zombie',
 'Mezuki',
 'Gozuki',
 'Zombie Master',
 'Shiranui Solitaire',
 'Necroworld Banshee',
 'Glow-Up Bloom',
 'Jack-o-Bolan',
 'Changshi the Spiridao',
 'Alghoul Mazera',
 'Mad Mauler',
 'Plaguespreader Zombie',
 'Tatsunecro',
 'Ghost Charon, the Underworld Boatman',
 'Vampire Fraulein',
 'Flying Mary, the Wandering Ghost Ship',
 'Vulcarrion the Rotting Phoenix',
 'The Duke of Demise',
 'Zombie World',
 'Zombie Necronize',
 'Zombie Power Struggle',
 'Book of Life',
 'Curse of the Ancient Turtle',
 'Ghost Fusion',
 'Super Polymerization',
 'Vampire Sucker',
 'Vampire Fascinator',
 'The Zombie Vampire',
 'Immortal Dragon',
 'Skeletal Dragon Felgrand',
 'Red-Eyes Zombie Necro Dragon',
 'Red-Eyes Zombie Dragon Lord',
 'Dragonecro Nethersoul Dragon',
 'Avendread Savior',
 'Samurai Skull',
 'Shinobi Necro',
 'Bone Archfiend',
 'Scapeghost',
 'Pyramid Turtle',
 'Goblin Zombie',
 'Il Blud',
 'Paladin of the Cursed Dragon',
 'Red-Eyes Zombie Dragon',
 'Yuki-Onna, the Absolute Zero Mayakashi',
 'Yuki-Onna, the Ice Mayakashi',
 'Return of the Zombies',
 'Haunted Zombies',
 'Zombie Reborn',
 'Burial from a Different Dimension',
 'Foolish Burial',
 'Reasoning',
 'Monster Gate',
 'One for One']
HALLOWEEN_PREVIEW_RELEASES: dict[str, dict[str, str]] = {
    "Magnificent Monsters": {"release_date": "2026-09-03", "label": "03/09/2026"},
    "Beyond the Brave": {"release_date": "2026-10-08", "label": "08/10/2026"},
}

HALLOWEEN_PREVIEW_DECKS: dict[str, dict[str, str]] = {
    "Ashtra": {"set": "Beyond the Brave", "release_date": "2026-10-08", "label": "Nouveau 2026"},
    "Umbral Horror": {"set": "Beyond the Brave", "release_date": "2026-10-08", "label": "Support 2026"},
}

HALLOWEEN_CARD_CATALOG: dict[str, dict[str, Any]] = {'Mitsurugi': {'archetypes': ['Mitsurugi']},
 'Memento': {'core_exact': ['Mementoal Tecuhtlica - Combined Creation',
                            'Mementomictlan',
                            'Mementomictlan Tecuhtlica - Creation King',
                            'Mementotlan Akihiron',
                            'Mementotlan Angwitch',
                            'Mementotlan Bone Back',
                            'Mementotlan Bone Party',
                            'Mementotlan Cranium Burst',
                            'Mementotlan Dark Blade',
                            'Mementotlan Fracture Dance',
                            'Mementotlan Fusion',
                            'Mementotlan Ghattic',
                            'Mementotlan Goblin',
                            'Mementotlan Mace',
                            'Mementotlan Shleepy',
                            'Mementotlan Tatsunootoshigo',
                            'Mementotlan Twin Dragon',
                            'Mementotlan-Horned Dragon'],
             'core_title': 'Archétype Memento',
             'expected_count': 18,
             'note': 'Catalogue figé à 18 cartes pour éviter qu’une requête d’API incomplète en masque deux.'},
 'Darklord': {'archetypes': ['Darklord'], 'staples': ['Forbidden Crown']},
 'Invoked': {'archetypes': ['Invoked'],
             'core_exact': ['Aleister the Invoker', 'Invocation', 'Magical Meltdown'],
             'related_exact': ['Invoked Mechaba', 'Invoked Purgatrio', 'Invoked Augoeides', 'Invoked Caliga', 'Invoked Raidjin', 'Invoked Cocytus', 'Invoked Elysium'],
             'note': 'Invoked rejoint le format Halloween comme branche occultisme / invocation et est classé S Tier.'},
 'Magical Musket': {'archetypes': ['Magical Musket', 'Magical Musketeer'],
                    'core_exact': ['Magical Musketeer Caspar', 'Magical Musketeer Starfire', 'Magical Musketeer Kidbrave', 'Magical Musketeer Doc', 'Magical Musketeer Wild', 'Magical Musketeer Calamity'],
                    'related_exact': ['Magical Musket - Cross-Domination', 'Magical Musket - Desperado', 'Magical Musket - Dancing Needle', 'Magical Musket - Last Stand', 'Magical Musket - Crooked Crown', 'Magical Musketeer Max'],
                    'note': 'Magical Musket rejoint le format Halloween avec une esthétique western gothique / pactes démoniaques.'},
 'D/D/D': {'archetypes': ['D/D', 'D/D/D']},
 'D/D': {'archetypes': ['D/D', 'D/D/D']},
 'Archfiend': {'archetypes': ['Archfiend'],
               'related_exact': ['Summoned Skull',
                                 'Toon Summoned Skull',
                                 'Beast of Talwar',
                                 'A Deal with Dark Ruler',
                                 'Matador Archfiend',
                                 'Ritual of the Matador'],
               'preview_exact': [{'name': "Archfiend's Origin",
                                  'set': "30th Anniversary Demon's Pack (OCG)",
                                  'tcg_legal': False,
                                  'ocg_release_date': '2026-05-28'}],
               'note': "Le catalogue ne se limite pas aux noms contenant Archfiend : le tag officiel de l'archétype est utilisé. Archfiend's Origin est affiché comme support annoncé OCG mais reste interdit tant qu'aucune sortie TCG n'est annoncée."},
 'Fiendsmith': {'archetypes': ['Fiendsmith']},
 'Unchained': {'archetypes': ['Unchained']},
 'Apophis': {'core_exact': ['Apophis the Serpent',
                            'Apophis the Swamp Deity',
                            'Divine Serpent Apophis',
                            'Embodiment of Apophis'],
             'related_exact': ['The Man with the Mark',
                               'Temple of the Kings',
                               'Treasures of the Kings',
                               'Defense of the Temple',
                               'Dangers of the Divine',
                               'Anubis the Last Judge',
                               'Merciless Scorpion of Serket',
                               'Mystical Beast of Serket'],
             'note': 'Le support Odion / Temple of the Kings est affiché comme support lié à Apophis.'},
 'Yubel': {'core_exact': ['Spirit of Yubel', 'Yubel', 'Yubel - Terror Incarnate', 'Yubel - The Ultimate Nightmare'],
           'extra_exact': ['Phantom of Yubel', 'Yubel - The Loving Defender Forever'],
           'support_exact': ['Geistgrinder Golem',
                             'Samsara D Lotus',
                             'Nightmare Throne',
                             'Mature Chronicle',
                             'Nightmare Pain',
                             'Eternal Favorite'],
           'related_exact': ['Gruesome Grave Squirmer',
                             'Neos Wiseman',
                             'Elemental HERO Neos Kluger',
                             'Super Polymerization'],
           'core_title': 'Monstres',
           'note': 'Yubel est séparé en Monstres / Extra Deck / Support / Related, conformément au catalogue de '
                   'référence.'},
 'Hecahands': {'archetypes': ['Hecahands']},
 'Azamina': {'archetypes': ['Azamina'],
             'staples': ['Deception of the Sinful Spoils',
                         'Diabellstar the Black Witch',
                         'WANTED: Seeker of Sinful Spoils',
                         'Sinful Spoils of Slumber - Morrian',
                         'Sinful Spoils of Subversion - Snake-Eye',
                         'Sinful Spoils of Betrayal - Silvera',
                         'Diabellstar Vengeance',
                         'Filia Diabell',
                         'Curse of Diabell',
                         'Like the Diabell',
                         'Guilt of the Sinful Spoils',
                         'Susurrus of the Sinful Spoils',
                         'The Black Goat Laughs',
                         'Astellar of the White Forest',
                         'Azamina Aphes',
                         'Beware the White Forest',
                         'Diabell, Queen of the White Forest',
                         'Diabellze the White Witch',
                         'Elzette of the White Forest',
                         'Elzette, Azamina of the White Forest',
                         'Poplar of the White Forest',
                         'Queen Azamina',
                         'Rciela, Sinister Soul of the White Forest',
                         'Rucia of the White Forest',
                         'Scourge of the White Forest',
                         'Silvera, Wolf Tamer of the White Forest',
                         'Silvy of the White Forest',
                         'Sinful Spoils of the White Forest',
                         'Tales of the White Forest',
                         'Witch of the White Forest',
                         'Woes of the White Forest'],
             'note': 'Le cœur Azamina reste séparé. White Forest, Sinful Spoils et Diabellstar associés apparaissent '
                     'dans Staples compatibles.',
             'staple_archetypes': ['White Forest']},
 'Ashtra': {'archetypes': ['Ashtra'],
            'preview_exact': [
                {'name': 'Akasuna the Battle Ashtra', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Kuzuha the Bewitching Deity Ashtra', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Yoa the Plague Deity Ashtra', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Mikumari the Sealing Deity Ashtra', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Ashtraja Susanoo', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Ashtraya Mikumari-no-Mikoto', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Ashtrashen - Gateway to the Worlds Beyond', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Ashtra Cursed Roar', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Ashtra Divine Domain', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                {'name': 'Ashtra Insect Poison', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
            ],
            'related_preview_exact': [
                {'name': 'Audhumla, Progenitor of the Frozen Expanse', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
            ],
            'expected_count': 10,
            'note': 'Nouvel archétype Halloween 2026. Les 10 cartes Ashtra sont affichées dès maintenant comme annoncées et deviennent légales automatiquement à partir du 08/10/2026. Audhumla apparaît en support lié.'},
 'K9': {'archetypes': ['K9']},
 'Snake-Eye': {'core_exact': ['Snake-Eye Ash',
                              'Snake-Eye Birch',
                              'Snake-Eye Oak',
                              'Snake-Eyes Poplar',
                              'Snake-Eyes Flamberge Dragon',
                              'Snake-Eyes Diabellstar',
                              'Snake-Eyes Doomed Dragon',
                              'Snake-Eyes Vengeance Dragon',
                              'Divine Temple of the Snake-Eye',
                              'Dramatic Snake-Eye Chase',
                              'Startling Stare of the Snake-Eyes',
                              'Original Sinful Spoils - Snake-Eye',
                              'Sinful Spoils of Subversion - Snake-Eye'],
               'staples': ['Bonfire'],
               'note': "Catalogue Snake-Eye explicite pour éviter qu'une partie de l'archétype disparaisse si le tag "
                       'API est incomplet.'},
 'Phantom Knights': {'core_exact': ["Phantom Knights' Fog Blade",
                                    "Phantom Knights' Rank-Up-Magic Force",
                                    "Phantom Knights' Spear",
                                    "Phantom Knights' Sword",
                                    "Phantom Knights' Wing",
                                    "Raider's Knight",
                                    "Raider's Unbreakable Mind",
                                    "Raider's Wing",
                                    "Raidraptor's Phantom Knights Claw",
                                    'The Phantom Knights of Ancient Cloak',
                                    'The Phantom Knights of Break Sword',
                                    'The Phantom Knights of Cloven Helm',
                                    'The Phantom Knights of Cursed Javelin',
                                    'The Phantom Knights of Dark Gauntlets',
                                    'The Phantom Knights of Decayed Cloak',
                                    'The Phantom Knights of Doomed Soleret',
                                    'The Phantom Knights of Fragile Armor',
                                    'The Phantom Knights of Lost Vambrace',
                                    'The Phantom Knights of Malevolent Scythe',
                                    'The Phantom Knights of Mist Claws',
                                    'The Phantom Knights of Ragged Gloves',
                                    'The Phantom Knights of Rusty Bardiche',
                                    'The Phantom Knights of Shade Brigandine',
                                    'The Phantom Knights of Shadow Veil',
                                    'The Phantom Knights of Silent Boots',
                                    'The Phantom Knights of Stained Greaves',
                                    'The Phantom Knights of Tomb Shield',
                                    'The Phantom Knights of Torn Scales',
                                    'The Phantom Knights of Umbrage Veil',
                                    'The Phantom Knights of Wrong Magnetring',
                                    "The Phantom Knights' Rank-Up-Magic Launch",
                                    "The Phantom Knights' Rank-Up-Magic Requiem"],
                     'related_exact': ['Dark Rebellion Xyz Dragon'],
                     'core_title': 'The Phantom Knights — 32 cartes',
                     'related_title': 'Related — 1 carte',
                     'expected_count': 33,
                     'note': '32 cartes appartiennent au set The Phantom Knights ; Dark Rebellion Xyz Dragon est '
                             'affiché séparément en Related, soit 33 cartes visibles.'},
 'Mimighoul': {'archetypes': ['Mimighoul']},
 'Thunder Dragon': {'archetypes': ['Thunder Dragon'], 'staples': ['Gold Sarcophagus', 'Chaos Space']},
 'Goblin Biker': {'core_exact': ['Goblin Biker Dugg Charger',
                                 'Goblin Biker Clatter Sploder',
                                 'Goblin Biker Mean Merciless',
                                 'Goblin Biker Boom Mach',
                                 'Goblin Bikers Gone Wild',
                                 'Goblin Biker Big Gabonga',
                                 'Goblin Biker Troika Griare',
                                 'Goblin Bikers Gone Bonkers',
                                 'Goblin Biker Grand Entrance',
                                 'Goblin Biker Grand Bash',
                                 'Goblin Biker Grand Breakout',
                                 'Goblin Biker Grand Pileup',
                                 'Goblin Biker Grand Crisis',
                                 'Goblin Rider Grand Crisis',
                                 'Goblin Biker Grand Stampede'],
                  'related_exact': ["Goblin's Crazy Beast"],
                  'note': "Liste explicite : Goblin Biker ne dépend plus d'une requête d'archétype fragile."},
 'Eldlich': {'archetypes': ['Eldlich', 'Eldlixir', 'Golden Land'],
             'staples': ['Skill Drain', 'Rivalry of Warlords', 'Gozen Match', 'There Can Be Only One']},
 'Zombie': {'core_exact': ['Zombie World', 'Doomking Balerdroch', 'Necroworld Banshee', 'Glow-Up Bloom'],
            'staples': ['Doomking Balerdroch',
                        'Uni-Zombie',
                        'Mezuki',
                        'Gozuki',
                        'Zombie Master',
                        'Shiranui Solitaire',
                        'Necroworld Banshee',
                        'Glow-Up Bloom',
                        'Jack-o-Bolan',
                        'Changshi the Spiridao',
                        'Alghoul Mazera',
                        'Mad Mauler',
                        'Plaguespreader Zombie',
                        'Tatsunecro',
                        'Ghost Charon, the Underworld Boatman',
                        'Vampire Fraulein',
                        'Flying Mary, the Wandering Ghost Ship',
                        'Vulcarrion the Rotting Phoenix',
                        'The Duke of Demise',
                        'Zombie World',
                        'Zombie Necronize',
                        'Zombie Power Struggle',
                        'Book of Life',
                        'Curse of the Ancient Turtle',
                        'Ghost Fusion',
                        'Super Polymerization',
                        'Vampire Sucker',
                        'Vampire Fascinator',
                        'The Zombie Vampire',
                        'Immortal Dragon',
                        'Skeletal Dragon Felgrand',
                        'Red-Eyes Zombie Necro Dragon',
                        'Red-Eyes Zombie Dragon Lord',
                        'Dragonecro Nethersoul Dragon',
                        'Avendread Savior',
                        'Chaos Ruler, the Chaotic Magical Dragon',
                        'That Grass Looks Greener',
                        'Samurai Skull',
                        'Shinobi Necro',
                        'Bone Archfiend',
                        'Scapeghost',
                        'Pyramid Turtle',
                        'Goblin Zombie',
                        'Il Blud',
                        'Paladin of the Cursed Dragon',
                        'Red-Eyes Zombie Dragon',
                        'Yuki-Onna, the Absolute Zero Mayakashi',
                        'Yuki-Onna, the Ice Mayakashi',
                        'Return of the Zombies',
                        'Haunted Zombies',
                        'Zombie Reborn',
                        'Burial from a Different Dimension',
                        'Foolish Burial',
                        'Reasoning',
                        'Monster Gate',
                        'One for One'],
            'note': 'Le noyau Zombie World est séparé des staples Zombie génériques.'},
 'Wight': {'core_exact': ['Skull Servant',
                          'King of the Skull Servants',
                          'The Lady in Wight',
                          'Wightprince',
                          'Wightprincess',
                          'Wightmare',
                          'Wightbaking',
                          'Wightlord',
                          'Moissa Wight',
                          'Wight Reanimator'],
           'related_exact': ['Flame Ghost'],
           'staples': ['One for One',
                       'That Grass Looks Greener',
                       'Doomking Balerdroch',
                       'Uni-Zombie',
                       'Mezuki',
                       'Gozuki',
                       'Zombie Master',
                       'Shiranui Solitaire',
                       'Necroworld Banshee',
                       'Glow-Up Bloom',
                       'Jack-o-Bolan',
                       'Changshi the Spiridao',
                       'Alghoul Mazera',
                       'Mad Mauler',
                       'Plaguespreader Zombie',
                       'Tatsunecro',
                       'Ghost Charon, the Underworld Boatman',
                       'Vampire Fraulein',
                       'Flying Mary, the Wandering Ghost Ship',
                       'Vulcarrion the Rotting Phoenix',
                       'The Duke of Demise',
                       'Zombie World',
                       'Zombie Necronize',
                       'Zombie Power Struggle',
                       'Book of Life',
                       'Curse of the Ancient Turtle',
                       'Ghost Fusion',
                       'Super Polymerization',
                       'Vampire Sucker',
                       'Vampire Fascinator',
                       'The Zombie Vampire',
                       'Immortal Dragon',
                       'Skeletal Dragon Felgrand',
                       'Red-Eyes Zombie Necro Dragon',
                       'Red-Eyes Zombie Dragon Lord',
                       'Dragonecro Nethersoul Dragon',
                       'Avendread Savior',
                       'Samurai Skull',
                       'Shinobi Necro',
                       'Bone Archfiend',
                       'Scapeghost',
                       'Pyramid Turtle',
                       'Goblin Zombie',
                       'Il Blud',
                       'Paladin of the Cursed Dragon',
                       'Red-Eyes Zombie Dragon',
                       'Yuki-Onna, the Absolute Zero Mayakashi',
                       'Yuki-Onna, the Ice Mayakashi',
                       'Return of the Zombies',
                       'Haunted Zombies',
                       'Zombie Reborn',
                       'Burial from a Different Dimension',
                       'Foolish Burial',
                       'Reasoning',
                       'Monster Gate']},
 'Gimmick Puppet': {'archetypes': ['Gimmick Puppet'],
                    'related_exact': ['Number 40: Gimmick Puppet of Strings',
                                      'Number C40: Gimmick Puppet of Dark Strings']},
 'Shaddoll': {'archetypes': ['Shaddoll'], 'staples': ['Instant Fusion', 'That Grass Looks Greener']},
 'Ogdoadic': {'archetypes': ['Ogdoadic'], 'staples': ['King of the Feral Imps', 'Foolish Burial']},
 'Nemleria': {'core_exact': ['Dreaming Nemleria',
                             'Dream Tower of Princess Nemleria',
                             'Sweet Dreams, Nemleria',
                             'Nemleria Dream Defender - Oreiller',
                             'Nemleria Dream Defender - Couette',
                             'Nemleria Dream Devourer - Reveil',
                             'Dreaming Reality of Nemleria, Realized',
                             'Nemleria Louve',
                             'Nemleria Repeter']},
 'Regenesis': {'archetypes': ['Regenesis']},
 'Fabled': {'archetypes': ['Fabled'],
            'staples': ['Card Destruction', 'T.G. Hyper Librarian', 'Borreload Savage Dragon']},
 'Umbral Horror': {'archetypes': ['Umbral Horror'],
                    'preview_exact': [
                        {'name': 'Shining Umbral Horror', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': 'V Umbral Horror', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': 'Gorgonic Umbral Horror', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': 'Thousand Umbral Horror', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': 'Number 104: Masquerade Vain', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': 'Number C104: Masquerade Umbral Horror Victory', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': 'CXyz Chaos Barian Hope Dragon', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': "Seventh Barian's", 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                        {'name': "Barian's Hope", 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                    ],
                    'related_exact': ['Number 104: Masquerade', 'Number C104: Umbral Horror Masquerade', "Rank-Up-Magic Limited Barian's Force"],
                    'expected_new_count': 9,
                    'note': 'Archétype Umbral Horror complet + vague de 9 cartes annoncée pour Beyond the Brave. Les nouvelles cartes sont visibles avant leur sortie et activées à partir du 08/10/2026.'},
 'Clown Crew': {'archetypes': ['Clown Crew'],
                'preview_exact': [{'name': 'Clown Crew Cappello',
                                   'set': 'Beyond the Brave',
                                   'release_date': '2026-10-08'}],
                'note': 'Archétype Clown Crew complet. Clown Crew Cappello est préchargé et devient légal automatiquement à la sortie TCG européenne de Beyond the Brave le 08/10/2026.'},
 'Generaider': {'archetypes': ['Generaider']},
 'Dark World': {'archetypes': ['Dark World'], 'staples': ['Card Destruction']},
 'Mayakashi': {'archetypes': ['Mayakashi'],
               'staples': ['Doomking Balerdroch',
                           'Uni-Zombie',
                           'Mezuki',
                           'Gozuki',
                           'Zombie Master',
                           'Shiranui Solitaire',
                           'Necroworld Banshee',
                           'Glow-Up Bloom',
                           'Jack-o-Bolan',
                           'Changshi the Spiridao',
                           'Alghoul Mazera',
                           'Mad Mauler',
                           'Plaguespreader Zombie',
                           'Tatsunecro',
                           'Ghost Charon, the Underworld Boatman',
                           'Vampire Fraulein',
                           'Flying Mary, the Wandering Ghost Ship',
                           'Vulcarrion the Rotting Phoenix',
                           'The Duke of Demise',
                           'Zombie World',
                           'Zombie Necronize',
                           'Zombie Power Struggle',
                           'Book of Life',
                           'Curse of the Ancient Turtle',
                           'Ghost Fusion',
                           'Super Polymerization',
                           'Vampire Sucker',
                           'Vampire Fascinator',
                           'The Zombie Vampire',
                           'Immortal Dragon',
                           'Skeletal Dragon Felgrand',
                           'Red-Eyes Zombie Necro Dragon',
                           'Red-Eyes Zombie Dragon Lord',
                           'Dragonecro Nethersoul Dragon',
                           'Avendread Savior',
                           'Samurai Skull',
                           'Shinobi Necro',
                           'Bone Archfiend',
                           'Scapeghost',
                           'Pyramid Turtle',
                           'Goblin Zombie',
                           'Il Blud',
                           'Paladin of the Cursed Dragon',
                           'Red-Eyes Zombie Dragon',
                           'Yuki-Onna, the Absolute Zero Mayakashi',
                           'Yuki-Onna, the Ice Mayakashi',
                           'Return of the Zombies',
                           'Haunted Zombies',
                           'Zombie Reborn',
                           'Burial from a Different Dimension',
                           'Foolish Burial',
                           'Reasoning',
                           'Monster Gate',
                           'One for One']},
 'Shiranui': {'archetypes': ['Shiranui'],
              'staples': ['Doomking Balerdroch',
                          'Uni-Zombie',
                          'Mezuki',
                          'Gozuki',
                          'Zombie Master',
                          'Shiranui Solitaire',
                          'Necroworld Banshee',
                          'Glow-Up Bloom',
                          'Jack-o-Bolan',
                          'Changshi the Spiridao',
                          'Alghoul Mazera',
                          'Mad Mauler',
                          'Plaguespreader Zombie',
                          'Tatsunecro',
                          'Ghost Charon, the Underworld Boatman',
                          'Vampire Fraulein',
                          'Flying Mary, the Wandering Ghost Ship',
                          'Vulcarrion the Rotting Phoenix',
                          'The Duke of Demise',
                          'Zombie World',
                          'Zombie Necronize',
                          'Zombie Power Struggle',
                          'Book of Life',
                          'Curse of the Ancient Turtle',
                          'Ghost Fusion',
                          'Super Polymerization',
                          'Vampire Sucker',
                          'Vampire Fascinator',
                          'The Zombie Vampire',
                          'Immortal Dragon',
                          'Skeletal Dragon Felgrand',
                          'Red-Eyes Zombie Necro Dragon',
                          'Red-Eyes Zombie Dragon Lord',
                          'Dragonecro Nethersoul Dragon',
                          'Avendread Savior',
                          'Samurai Skull',
                          'Shinobi Necro',
                          'Bone Archfiend',
                          'Scapeghost',
                          'Pyramid Turtle',
                          'Goblin Zombie',
                          'Il Blud',
                          'Paladin of the Cursed Dragon',
                          'Red-Eyes Zombie Dragon',
                          'Yuki-Onna, the Absolute Zero Mayakashi',
                          'Yuki-Onna, the Ice Mayakashi',
                          'Return of the Zombies',
                          'Haunted Zombies',
                          'Zombie Reborn',
                          'Burial from a Different Dimension',
                          'Foolish Burial',
                          'Reasoning',
                          'Monster Gate',
                          'One for One']},
 'Call of the Haunted / Pumpking': {'core_exact': ['Call of the Haunted',
                                                   'Pumpking the King of Grave Ghosts',
                                                   'Army of the Haunted',
                                                   'Stare of the Snake Hair',
                                                   'Great Mammoth of the Netherworld',
                                                   'Call of the Forgotten',
                                                   'Ectoplasmic Fortification',
                                                   'Vortex of Time',
                                                   'Deadly Zombie Breath'],
                                    'extra_exact': ['Pumpking the Great Ghost King', 'The Undying Legion'],
                                    'related_exact': ['Pumpking the King of Ghosts',
                                                      'The Snake Hair',
                                                      'Great Mammoth of Goldfine',
                                                      'Armored Zombie',
                                                      'Clown Zombie',
                                                      'Dragon Zombie'],
                                    'staples': ['Card of Safe Return',
                                                'Doomking Balerdroch',
                                                'Uni-Zombie',
                                                'Mezuki',
                                                'Gozuki',
                                                'Zombie Master',
                                                'Shiranui Solitaire',
                                                'Necroworld Banshee',
                                                'Glow-Up Bloom',
                                                'Jack-o-Bolan',
                                                'Changshi the Spiridao',
                                                'Alghoul Mazera',
                                                'Mad Mauler',
                                                'Plaguespreader Zombie',
                                                'Tatsunecro',
                                                'Ghost Charon, the Underworld Boatman',
                                                'Vampire Fraulein',
                                                'Flying Mary, the Wandering Ghost Ship',
                                                'Vulcarrion the Rotting Phoenix',
                                                'The Duke of Demise',
                                                'Zombie World',
                                                'Zombie Necronize',
                                                'Zombie Power Struggle',
                                                'Book of Life',
                                                'Curse of the Ancient Turtle',
                                                'Ghost Fusion',
                                                'Super Polymerization',
                                                'Vampire Sucker',
                                                'Vampire Fascinator',
                                                'The Zombie Vampire',
                                                'Immortal Dragon',
                                                'Skeletal Dragon Felgrand',
                                                'Red-Eyes Zombie Necro Dragon',
                                                'Red-Eyes Zombie Dragon Lord',
                                                'Dragonecro Nethersoul Dragon',
                                                'Avendread Savior',
                                                'Samurai Skull',
                                                'Shinobi Necro',
                                                'Bone Archfiend',
                                                'Scapeghost',
                                                'Pyramid Turtle',
                                                'Goblin Zombie',
                                                'Il Blud',
                                                'Paladin of the Cursed Dragon',
                                                'Red-Eyes Zombie Dragon',
                                                'Yuki-Onna, the Absolute Zero Mayakashi',
                                                'Yuki-Onna, the Ice Mayakashi',
                                                'Return of the Zombies',
                                                'Haunted Zombies',
                                                'Zombie Reborn',
                                                'Burial from a Different Dimension',
                                                'Foolish Burial',
                                                'Reasoning',
                                                'Monster Gate',
                                                'One for One'],
                                    'note': 'Package Call of the Haunted / Pumpking enrichi avec le support Maze of '
                                            'Muertos, les deux Xyz dédiés et les anciennes cartes de Bonz.'},
 'Altergeist': {'archetypes': ['Altergeist'], 'staples': ["Vanity's Emptiness", 'Imperial Order', 'Summon Limit']},
 'Evil Eye': {'archetypes': ['Evil Eye'], 'staples': ['Kaiser Colosseum']},
 'Blackwing': {'archetypes': ['Blackwing']},
 'Eyes Restrict / Relinquished': {'core_exact': ['Relinquished',
                                                 'Relinquished Anima',
                                                 'Relinquished Fusion',
                                                 'Black Illusion Ritual',
                                                 'Thousand-Eyes Restrict',
                                                 'Millennium-Eyes Restrict',
                                                 'Millennium-Eyes Illusionist',
                                                 'Golden-Eyes Idol',
                                                 'Illusionist Faceless Magician',
                                                 'Thousand-Eyes Idol'],
                                  'preview_exact': [
                                      {'name': 'Nightmare-Eyes Restrict', 'set': 'Magnificent Monsters', 'release_date': '2026-09-03'},
                                  ],
                                  'note': 'Nightmare-Eyes Restrict est affiché comme carte annoncée puis devient légal automatiquement à partir du 03/09/2026.'},
 'Evil HERO': {'archetypes': ['Evil HERO'], 'staples': ['Predaplant Verte Anaconda']},
 'Vampire': {'archetypes': ['Vampire'],
             'staples': ['Card of Safe Return',
                         'Doomking Balerdroch',
                         'Uni-Zombie',
                         'Mezuki',
                         'Gozuki',
                         'Zombie Master',
                         'Shiranui Solitaire',
                         'Necroworld Banshee',
                         'Glow-Up Bloom',
                         'Jack-o-Bolan',
                         'Changshi the Spiridao',
                         'Alghoul Mazera',
                         'Mad Mauler',
                         'Plaguespreader Zombie',
                         'Tatsunecro',
                         'Ghost Charon, the Underworld Boatman',
                         'Vampire Fraulein',
                         'Flying Mary, the Wandering Ghost Ship',
                         'Vulcarrion the Rotting Phoenix',
                         'The Duke of Demise',
                         'Zombie World',
                         'Zombie Necronize',
                         'Zombie Power Struggle',
                         'Book of Life',
                         'Curse of the Ancient Turtle',
                         'Ghost Fusion',
                         'Super Polymerization',
                         'Vampire Sucker',
                         'Vampire Fascinator',
                         'The Zombie Vampire',
                         'Immortal Dragon',
                         'Skeletal Dragon Felgrand',
                         'Red-Eyes Zombie Necro Dragon',
                         'Red-Eyes Zombie Dragon Lord',
                         'Dragonecro Nethersoul Dragon',
                         'Avendread Savior',
                         'Samurai Skull',
                         'Shinobi Necro',
                         'Bone Archfiend',
                         'Scapeghost',
                         'Pyramid Turtle',
                         'Goblin Zombie',
                         'Il Blud',
                         'Paladin of the Cursed Dragon',
                         'Red-Eyes Zombie Dragon',
                         'Yuki-Onna, the Absolute Zero Mayakashi',
                         'Yuki-Onna, the Ice Mayakashi',
                         'Return of the Zombies',
                         'Haunted Zombies',
                         'Zombie Reborn',
                         'Burial from a Different Dimension',
                         'Foolish Burial',
                         'Reasoning',
                         'Monster Gate',
                         'One for One']},
 'Scareclaw': {'archetypes': ['Scareclaw'], 'staples': ['Knightmare Gryphon']},
 'Myutant': {'archetypes': ['Myutant'], 'staples': ['Dimension Shifter', 'Return from the Different Dimension']},
 'Fluffal / Frightfur': {'archetypes': ['Fluffal', 'Frightfur', 'Edge Imp'], 'staples': ['Predaplant Verte Anaconda']},
 'Arcana Force': {'archetypes': ['Arcana Force'], 'staples': ['Sixth Sense']},
 'Spirit Message': {'core_exact': ['Destiny Board',
                                   'Spirit Message "I"',
                                   'Spirit Message "N"',
                                   'Spirit Message "A"',
                                   'Spirit Message "L"'],
                    'support_exact': ['Dark Sanctuary',
                                      "Dark Spirit's Mastery",
                                      'Sentence of Doom',
                                      'Spirit Shield',
                                      'Spirit Illusion',
                                      'Dark Necrofear',
                                      'Curse Necrofear',
                                      'Dark Spirit of Banishment',
                                      'Dark Spirit of Malice',
                                      'Dark Spirit of the Silent',
                                      'The Duke of Demise',
                                      'Zoma the Spirit',
                                      'Zoma the Earthbound Spirit'],
                    'core_title': 'Destiny Board / Spirit Messages (F I N A L)',
                    'staples': ['Mystic Mine', 'One Day of Peace', 'Card of Demise'],
                    'note': 'Spirit Message inclut davantage de supports Bakura / Destiny Board et sépare les staples '
                            'Halloween.'},
 'Ghostrick': {'archetypes': ['Ghostrick'], 'staples': ['Royal Oppression', 'One Day of Peace', 'Card of Demise']},
 'Yo-kai Girl': {'core_exact': ['Ash Blossom & Joyous Spring',
                                'Ghost Ogre & Snow Rabbit',
                                'Ghost Belle & Haunted Mansion',
                                'Ghost Reaper & Winter Cherries',
                                'Ghost Sister & Spooky Dogwood',
                                'Ghost Mourner & Moonlit Chill']},
 'Knightmare': {'archetypes': ['Knightmare']},
 'Danger!': {'archetypes': ['Danger!']},
 'Paleozoic': {'archetypes': ['Paleozoic']},
 'Predaplant': {'archetypes': ['Predaplant'],
                 'preview_exact': [{'name': 'Predaplant Daredevil',
                                    'set': 'Beyond the Brave',
                                    'release_date': '2026-10-08'}],
                 'note': 'Predaplant Daredevil est préchargé et devient légal automatiquement le 08/10/2026 avec Beyond the Brave.'},
 'Entity': {'archetypes': ['Entity']},
 'Evilswarm': {'archetypes': ['Evilswarm']},
 'True King': {'archetypes': ['True King']},
 'Halloween Staples': {'core_exact': ['Forbidden Crown',
                                      'Bonfire',
                                      'Gold Sarcophagus',
                                      'Chaos Space',
                                      'Skill Drain',
                                      'Rivalry of Warlords',
                                      'Gozen Match',
                                      'There Can Be Only One',
                                      'Chaos Ruler, the Chaotic Magical Dragon',
                                      'That Grass Looks Greener',
                                      'One for One',
                                      'Instant Fusion',
                                      'Foolish Burial',
                                      'King of the Feral Imps',
                                      'Card Destruction',
                                      'T.G. Hyper Librarian',
                                      'Borreload Savage Dragon',
                                      "Vanity's Emptiness",
                                      'Imperial Order',
                                      'Summon Limit',
                                      'Kaiser Colosseum',
                                      'Predaplant Verte Anaconda',
                                      'Card of Safe Return',
                                      'Knightmare Gryphon',
                                      'Dimension Shifter',
                                      'Return from the Different Dimension',
                                      'Sixth Sense',
                                      'Mystic Mine',
                                      'One Day of Peace',
                                      'Card of Demise',
                                      'Royal Oppression'],
                       'note': "Vue d'ensemble des cartes génériques. Leur limite peut dépendre du deck autorisé qui "
                               'les utilise.',
                       'staple_overview': True},
 'Halloween 2026 — Cartes annoncées': {'preview_exact': [
                                         {'name': 'Foolish Graverobber', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                         {'name': 'Destiny HERO - Doom Overlord', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                         {'name': 'Destiny HERO - Destro-Dogma', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                         {'name': 'Destiny HERO - Dreadnought Master', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                         {'name': 'Dark City at Midnight', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                         {'name': 'Orichalcos Sword of Sealing', 'set': 'Magnificent Monsters', 'release_date': '2026-09-03'},
                                     ],
                                     'preview_archetypes': [
                                         {'archetype': 'Ars Magna', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                         {'archetype': 'Theorealize', 'set': 'Beyond the Brave', 'release_date': '2026-10-08'},
                                     ],
                                     'core_title': 'Cartes annoncées compatibles Halloween',
                                     'staple_overview': True,
                                     'note': 'Pool 2026 : cartes occultes / macabres annoncées avant Halloween. Elles restent visibles avant leur sortie mais ne sont considérées légales qu’à partir de la date TCG indiquée.'},
 'Zombie Staples': {'core_exact': ['Doomking Balerdroch',
                                   'Uni-Zombie',
                                   'Mezuki',
                                   'Gozuki',
                                   'Zombie Master',
                                   'Shiranui Solitaire',
                                   'Necroworld Banshee',
                                   'Glow-Up Bloom',
                                   'Jack-o-Bolan',
                                   'Changshi the Spiridao',
                                   'Alghoul Mazera',
                                   'Mad Mauler',
                                   'Plaguespreader Zombie',
                                   'Tatsunecro',
                                   'Ghost Charon, the Underworld Boatman',
                                   'Vampire Fraulein',
                                   'Flying Mary, the Wandering Ghost Ship',
                                   'Vulcarrion the Rotting Phoenix',
                                   'The Duke of Demise',
                                   'Zombie World',
                                   'Zombie Necronize',
                                   'Zombie Power Struggle',
                                   'Book of Life',
                                   'Curse of the Ancient Turtle',
                                   'Ghost Fusion',
                                   'Super Polymerization',
                                   'Vampire Sucker',
                                   'Vampire Fascinator',
                                   'The Zombie Vampire',
                                   'Immortal Dragon',
                                   'Skeletal Dragon Felgrand',
                                   'Red-Eyes Zombie Necro Dragon',
                                   'Red-Eyes Zombie Dragon Lord',
                                   'Dragonecro Nethersoul Dragon',
                                   'Avendread Savior',
                                   'Samurai Skull',
                                   'Shinobi Necro',
                                   'Bone Archfiend',
                                   'Scapeghost',
                                   'Pyramid Turtle',
                                   'Goblin Zombie',
                                   'Il Blud',
                                   'Paladin of the Cursed Dragon',
                                   'Red-Eyes Zombie Dragon',
                                   'Yuki-Onna, the Absolute Zero Mayakashi',
                                   'Yuki-Onna, the Ice Mayakashi',
                                   'Return of the Zombies',
                                   'Haunted Zombies',
                                   'Zombie Reborn',
                                   'Burial from a Different Dimension',
                                   'Foolish Burial',
                                   'Reasoning',
                                   'Monster Gate',
                                   'One for One'],
                    'core_title': 'Staples Zombie',
                    'staple_overview': True,
                    'note': 'Pool Zombie élargi : starters, extenders, moteurs Cimetière, boss et cartes de '
                            'résurrection.'}}
HALLOWEEN_REPRESENTATIVE_CARDS: dict[str, str | None] = {'Mitsurugi': 'Ame no Habakiri no Mitsurugi',
 'Memento': 'Mementoal Tecuhtlica - Combined Creation',
 'Darklord': 'The First Darklord',
 'Invoked': 'Aleister the Invoker',
 'Magical Musket': 'Magical Musketeer Max',
 'D/D/D': 'D/D/D Deviser King Deus Machinex',
 'D/D': 'D/D Savant Kepler',
 'Archfiend': 'Red Dragon Archfiend',
 'Fiendsmith': 'Fiendsmith Engraver',
 'Unchained': 'Unchained Abomination',
 'Apophis': 'Apophis the Swamp Deity',
 'Yubel': 'Yubel - The Loving Defender Forever',
 'Hecahands': None,
 'Azamina': 'Queen Azamina',
 'Ashtra': 'Ashtraja Susanoo',
 'K9': None,
 'Snake-Eye': 'Snake-Eyes Flamberge Dragon',
 'Phantom Knights': 'The Phantom Knights of Rusty Bardiche',
 'Mimighoul': 'Mimighoul Master',
 'Thunder Dragon': 'Thunder Dragon Colossus',
 'Goblin Biker': 'Goblin Biker Big Gabonga',
 'Eldlich': 'Eldlich the Golden Lord',
 'Zombie': 'Doomking Balerdroch',
 'Wight': 'King of the Skull Servants',
 'Gimmick Puppet': 'CXyz Gimmick Puppet Fanatix Machinix',
 'Shaddoll': 'El Shaddoll Construct',
 'Ogdoadic': 'Ogdoabyss, the Ogdoadic Overlord',
 'Nemleria': 'Dreaming Nemleria',
 'Regenesis': None,
 'Fabled': 'Fabled Leviathan',
 'Umbral Horror': 'Number C104: Masquerade Umbral Horror Victory',
 'Clown Crew': 'Clown Crew Biancaviso',
 'Generaider': 'Jormungandr, Generaider Boss of Eternity',
 'Dark World': 'Grapha, Dragon Overlord of Dark World',
 'Mayakashi': 'Yuki-Onna, the Absolute Zero Mayakashi',
 'Shiranui': 'Shiranui Sunsaga',
 'Call of the Haunted / Pumpking': None,
 'Altergeist': 'Altergeist Adminia',
 'Evil Eye': 'Serziel, Watcher of the Evil Eye',
 'Blackwing': 'Black-Winged Assault Dragon',
 'Eyes Restrict / Relinquished': 'Millennium-Eyes Restrict',
 'Evil HERO': 'Evil HERO Malicious Bane',
 'Vampire': 'The Zombie Vampire',
 'Scareclaw': 'Scareclaw Tri-Heart',
 'Myutant': 'Myutant Ultimus',
 'Fluffal / Frightfur': 'Frightfur Sabre-Tooth',
 'Arcana Force': 'Arcana Force XXI - The World',
 'Spirit Message': 'Destiny Board',
 'Ghostrick': 'Ghostrick Angel of Mischief',
 'Yo-kai Girl': 'Ash Blossom & Joyous Spring',
 'Knightmare': 'Knightmare Unicorn',
 'Danger!': 'Danger! Bigfoot!',
 'Paleozoic': 'Paleozoic Opabinia',
 'Predaplant': 'Predaplant Triphyoverutum',
 'Entity': "Elder Entity N'tss",
 'Evilswarm': 'Evilswarm Exciton Knight',
 'True King': 'True King of All Calamities',
 'Zombie Staples': 'Doomking Balerdroch',
 'Halloween Staples': 'Dark Hole',
 'Halloween 2026 — Cartes annoncées': 'Foolish Graverobber'}
HALLOWEEN_CANDIES: list[str] = ['Pot of Duality',
 'One Day of Peace',
 'Book of Moon',
 'Allure of Darkness',
 'Monster Reborn',
 'Upstart Goblin',
 'Creature Swap',
 'Forbidden Chalice']
HALLOWEEN_SPELLS: list[str] = ['Card Destruction',
 'Mind Control',
 'Enemy Controller',
 'Eradicator Epidemic Virus',
 'Offerings to the Doomed',
 'Dark Hole',
 'Terraforming',
 'Mystical Space Typhoon']


def _slug(value: str) -> str:
    text = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    text = text.lower().replace("&", "and").replace("/", "-").replace("!", "")
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def _image_slug(name: str) -> str:
    if name == "Call of the Haunted / Pumpking": return "call-of-the-haunted-pumpking"
    if name == "Zombie Staples": return "zombie-staples"
    if name == "Halloween Staples": return "halloween-staples"
    return _slug(name)


def _entry(name: str, tier: str) -> dict[str, Any]:
    entry = {"name":name,"slug":_slug(name),"image_url":f"/static/halloween/decks/{_image_slug(name)}.jpg","tier":tier,"overrides":deepcopy(HALLOWEEN_BANLIST_OVERRIDES.get(name,[]))}
    preview = HALLOWEEN_PREVIEW_DECKS.get(name)
    if preview:
        entry["release_label"] = preview.get("label", "2026")
        entry["release_date"] = preview.get("release_date")
        entry["release_set"] = preview.get("set")
    return entry


class HalloweenFormatService:
    def public_data(self) -> dict[str, Any]:
        tiers=deepcopy(HALLOWEEN_TIERS)
        for tier in tiers: tier["entries"]=[_entry(name,tier["id"]) for name in tier["decks"]]
        staples=[_entry(name,"STAPLE") for name in HALLOWEEN_STAPLES]
        catalog_payload={"catalog":HALLOWEEN_CARD_CATALOG,"overrides":HALLOWEEN_BANLIST_OVERRIDES,"global_bans":HALLOWEEN_GLOBAL_BANS,"representative_cards":HALLOWEEN_REPRESENTATIVE_CARDS,"tiers":HALLOWEEN_TIERS,"staples":HALLOWEEN_STAPLES,"preview_releases":HALLOWEEN_PREVIEW_RELEASES}
        return {
            "id":"halloween","name":"Halloween","emoji":"🎃","format_version":"6.0",
            "description":"Format Halloween Hamtaro V8 : Invoked en S Tier, Magical Musket ajouté, artworks personnalisés verrouillés, banlist spéciale et mécanique Bonbon / Sort.",
            "meta_left":"Whitelist Halloween V6","meta_right":f"{sum(len(t['decks']) for t in HALLOWEEN_TIERS)} decks + {len(HALLOWEEN_STAPLES)} groupes de staples",
            "tiers":tiers,"staples":staples,"global_bans":list(HALLOWEEN_GLOBAL_BANS),"banlist_overrides":deepcopy(HALLOWEEN_BANLIST_OVERRIDES),
            "candies":list(HALLOWEEN_CANDIES),"spells":list(HALLOWEEN_SPELLS),"card_catalog_json":json.dumps(catalog_payload,ensure_ascii=False),
        }

    def whitelist_text(self) -> str:
        lines=[]
        for tier in HALLOWEEN_TIERS:
            lines.append(f"[{tier['label']}]"); lines.extend(f"- {name}" for name in tier["decks"]); lines.append("")
        lines.append("[STAPLES]"); lines.extend(f"- {name}" for name in HALLOWEEN_STAPLES)
        return "\n".join(lines).rstrip()+"\n"

    def banlist_text(self) -> str:
        lines=["FORMAT HALLOWEEN V6 - BANLIST SPÉCIALE","Toute carte absente suit la banlist TCG normale.","","[INTERDITES GLOBALEMENT]"]
        lines.extend(f"- {card} : x0" for card in HALLOWEEN_GLOBAL_BANS); lines.append("")
        for deck,entries in HALLOWEEN_BANLIST_OVERRIDES.items():
            if not entries: continue
            lines.append(f"[{deck}]"); lines.extend(f"- {e['card']} : x{e['limit']}" for e in entries); lines.append("")
        return "\n".join(lines).rstrip()+"\n"
